### ISSUE TITLE
User.licence missing

### ISSUE THREAD

**Issue by Loleyy** [ESX-Org/esx_dmvschool#1]
Hi guys,

I put the .sql licence + dvmshcool licence and i got than error : 

[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM user_licenses WHERE owner = @owner {@owner=steam:110000101e9c85a}": Table 'essentialmode.user_licenses' doesn't exist

Did u forget the user.licence sql somewhere ? ^^

**Comment by RomainLanz** [comment]
Hey @Loleyy! 👋 

Fixed in https://github.com/ESX-Org/esx_license/commit/b4134e20117124d050c13d2dcf2987b6f3cb50d5
