### ISSUE TITLE
After failing the first theoretical test, starting second time freezes screen

### ISSUE THREAD

**Issue by GigaBytesAGRP** [ESX-Org/esx_dmvschool#14]
If you do the test and fail, You can't re do the test again. It will re open the menu (Nui Focus) and charge you the money, but you cant click anything inside the menu. You must Alt F4 to exit the server

**Comment by EGUltraTM** [comment]
yep same here

**Comment by nearbyplayer** [comment]
Submit a PR with your fix.

**Comment by six-sens** [comment]
I try very hard to find what part of rhe code dont let me retry de theory test.
Anyone have an idea?

**Comment by ElPumpo** [comment]
Fixed in https://github.com/ESX-Org/esx_dmvschool/pull/19 thanks to Anthony!
