### ISSUE TITLE
Translation mistake ?

### ISSUE THREAD

**Issue by Geant200** [ESX-Org/esx_dmvschool#32]
I am having problems with translation

I tested the translations Fr - Br - In Toujour the same message in the menu to pass the permit truck.

I try to translate languange files from En to Fr it does not work either always the same message.

Here are the links in image of the menu.

http://utilitaire.war-team.com/autre/gta5rp/images/bug/traduction.jpg

I thank you in advance for the solution.

**Comment by Geant200** [comment]
Can you help me please ?.

**Comment by rex2630** [comment]
This was fixed in this commit: https://github.com/ESX-Org/esx_dmvschool/commit/168cb1710f40eba0f9437540bac6cd68225520e6 Thanks for reporting :)
