### ISSUE TITLE
PSA: All builds, including the Master Build, are incompatible with the newest Mater Build of es_extended

### ISSUE THREAD

**Issue by xlimeTigerx** [ESX-Org/esx_dmvschool#39]
Yo ElPumpo, just thought I'd let you know this doesn't work with the latest master build of es_extended.

I tried the latest Master release of esx_dmvschool, the latest Release of esx_dmvschool, and none of them work.

I then copied the version of my old ESX server, which ran on the latest Release build of es_extended, and worked as of 2 hours ago, and that doesn't work either with the newest build.

It specifically breaks when you 'Press E' to open the menu.

Just a little reminder :)

**Comment by Fluffyss** [comment]
Where did you downloaded them (updates) from?
I tried to update, doesnt work here sadly.
