### ISSUE TITLE
Change to English

### ISSUE THREAD

**Issue by clumsyzombie** [ESX-Org/esx_dmvschool#4]
Was wondering I change all the stuff to en. and also even in the html renamed the _en file and then on thee french ones add _fr and still is picking the french version. What am i doing wrong please help

**Comment by eagledude4** [comment]
changed the _resouces.lua to include
`ui_page 'html/ui_en.html'`
`files {
  'html/ui_en.html',
  'html/logo.png',
  'html/dmv.png',
  'html/cursor.png',
  'html/styles.css',
  'html/questions.js',
  'html/scripts.js',
  'html/debounce.min.js'
}`

but there is nothing dispalyed, and the menu can't be exitted.

**Comment by shortybsd** [comment]
Also edit ui_en.html and change line 116 to reflect `<script src="questions_en.js" type="text/javascript"></script>` or else the questions will show up blank!
