### ISSUE TITLE
Error running system event handling function for resource esx_dmvschool

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_dmvschool#8]
How can i fix this:

Error running system event handling function for resource esx_dmvschool: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/locale.lua:8: bad argument #2 to 'format' (no value)
stack traceback:
	[C]: in function 'string.format'
	@es_extended/locale.lua:8: in function '_'
	@es_extended/locale.lua:20: in function '_U'
	server/main.lua:32: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

**Comment by ElPumpo** [comment]
The locale you're using has not been updated.
